### ISSUE TITLE
Hardcoded dependencies become outdated

### ISSUE THREAD

**Issue by BWsix** [line/create-liff-app#11]
Hi, I really enjoy using this package to quickly generate liff projects, but I found some issues with outdated dependencies.

Currently, dependencies are hardcoded into `package.json`s and some have already become outdated.
I looked into how [`create-next-app`](https://github.com/vercel/next.js/tree/canary/packages/create-next-app) handles this issue and found that they install all the dependencies using spawn in runtime to get the latest versions of dependencies. Below is a demonstration of how they do it: ([source code](https://github.com/vercel/next.js/blob/bb7b75809d3bfc813034e4002e5e9212a612a75f/packages/create-next-app/create-app.ts#L227))

```ts
const dependencies = ['react', 'react-dom', 'next'];
spawn(packageManager, dependencies);
```

You'll gain two benefits from implementing this method:
1. Manual updates of the `liff` package are no longer needed
2. Up-to-date dependencies

If you think this is a good idea, just let me know and I could try to make a PR for this.
Btw, all the linebreaks in this project are `CRLF`, not `LF` as defined in `.eslint.js`. And there is no configuration file for installed dev-dependency `prettier`.

**Comment by so99ynoodles** [comment]
@BWsix First of all, thank you for your continuous contribution! 🙇‍♂️ 
Let me talk with the LIFF team about this issue.

**Comment by BWsix** [comment]
I see!

**Comment by so99ynoodles** [comment]
@BWsix 
We discussed and would like you to create the PR for this issue! There are some concerns like the stability of the dependencies or build settings of the templates but we would like to discuss them in the PR review in detail.

**Comment by BWsix** [comment]
@so99ynoodles 
Sure! I'll work on it asap.
